version: "3.8"

services:
  yew:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ..:/workspace:cached
    working_dir: /workspace
    command: trunk serve --address 0.0.0.0 --port 3000
